
s3_bucket: codegram-web
s3_access_key_id: <%= ENV['S3_KEY'] %>
s3_secret_access_key: <%= ENV['S3_SECRET'] %>
s3_cache_control: public, max-age=<%= 365 * 24 * 60 * 60 %>
embed_assets: datauri

javascripts:
  workspace:
    - public/javascripts/workspace/jquery.min.js
    - public/javascripts/workspace/scrollable.js
    - public/javascripts/workspace/**/*.js
  application:
    - public/javascripts/application/application.js
stylesheets:
  common:
    - public/stylesheets/screen.css
    - public/stylesheets/markdownizer.css
  print:
    - public/stylesheets/print.css

