embed_assets: on
javascripts:
  workspace:
    - public/javascripts/jquery.min.js
    - public/javascripts/**/*
stylesheets:
  common:
    - public/stylesheets/screen.css
  print:
    - public/stylesheets/print.css

