embed_assets: on

javascripts:
  workspace:
    - public/javascripts/workspace/jquery.tools.min.js
    - public/javascripts/workspace/**/*.js
  application:
    - public/javascripts/application/application.js
stylesheets:
  common:
    - public/stylesheets/screen.css
  print:
    - public/stylesheets/print.css

